# Generated by Django 3.1.5 on 2021-03-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_trail',
            field=models.BooleanField(default=True),
        ),
    ]
