# Generated by Django 3.1.5 on 2021-03-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_information', '0003_auto_20210310_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='package',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='company_site',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, default='images/logo.png', upload_to='images/logo'),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
