# Generated by Django 3.1.5 on 2021-03-15 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0002_auto_20210314_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('ref', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('contact', models.ManyToManyField(to='contacts.Contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
