# Generated by Django 3.1.5 on 2021-03-27 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0002_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='', max_length=255)),
                ('delivered', models.IntegerField(default=0)),
                ('total_emails', models.IntegerField(default=0)),
                ('clicked', models.IntegerField(default=0)),
                ('opened', models.IntegerField(default=0)),
                ('invalid', models.IntegerField(default=0)),
                ('unsubscribed', models.IntegerField(default=0)),
                ('bounced', models.IntegerField(default=0)),
                ('sent_emails', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_sent', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default='Not yet started', max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('clist', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('replyTo', models.CharField(max_length=255)),
                ('redirect_urls', models.CharField(max_length=300)),
                ('first_email', models.IntegerField(default=1)),
                ('time_delta', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
