# Generated by Django 3.1.5 on 2021-03-27 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0004_auto_20210315_1209'),
        ('campaigns', '0003_campaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='email',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='first_email',
        ),
        migrations.CreateModel(
            name='MessageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('message_id', models.CharField(default='', max_length=100)),
                ('thread_id', models.CharField(default='', max_length=100)),
                ('unsubscribe', models.CharField(default='no', max_length=3)),
                ('sent', models.BooleanField(default=False)),
                ('bounced', models.CharField(default='no', max_length=3)),
                ('invalid', models.CharField(default='no', max_length=3)),
                ('clicks', models.IntegerField(default=0)),
                ('opens', models.IntegerField(default=0)),
                ('sent_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
